### ISSUE TITLE
Release update on Pypi

### ISSUE THREAD

**Issue by veeshi** [linuxscout/alyahmor#1]
السلام عليكم ورحمة الله وبركاته،

The current version on Pypi errors out on importing with

```Python console
>>> from alyahmor import genelex
Traceback (most recent call last):
  File "<console>", line 1, in <module>                                                                                                                                
  File "/home/xxxxxxx/xxx/env/lib/python3.7/site-packages/alyahmor/genelex.py", line 28, in <module>                                             
    import noun_affixer                                                                                                                                                
ModuleNotFoundError: No module named 'noun_affixer'
```

The last commit 654813ecd41ff0bcae14b82b40f18b1baa534962 has fixed this issue.

جزاكم الله خيراً وأحسن الجزاء

**Comment by linuxscout** [comment]
Thanks for this note, 
I just uploaded a new version
Thanks

**Comment by veeshi** [comment]
شكرا لجوابك السريعة!

جزاكم الله خيراً وأحسن الجزاء
